/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2018-2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __RTE_DEVICE_H
#define __RTE_DEVICE_H

/***********************************************************************************************************************
 * Driver name mapping
 **********************************************************************************************************************/
/* Enable peripheral */
#define RTE_USART4 1

/***********************************************************************************************************************
 * Driver configuration
 **********************************************************************************************************************/
/* All USART Rx buffers length */
#define USART_RX_BUFFER_LEN 64
/* Enable RX buffer */
#define USART4_RX_BUFFER_ENABLE 0


#endif /* __RTE_DEVICE_H */
